## Pipeline

Useful method for pre-processing the galaxy object to perform  transform methods with a final decomposer.

Sequentially apply a list of transforms and a final decomposer.
The purpose of the pipeline is to assemble several steps that can be applied together while setting different parameters.

In [1]:
import galaxychop as gchop

gal = gchop.io.read_hdf5("../../../tests/datasets/gal394242.h5")
gal

In [2]:
center = gchop.preproc.Centralizer()
align = gchop.preproc.Aligner(r_cut=30) 

print("Centered:", center.checker(gal))
print("Aligned:", align.checker(gal))

Centered: False
Aligned: False

Here an example that performs the aligner, the centralizer and after that the `JThreshold` decomposer

In [3]:
Centralizer = gchop.preproc.Centralizer(with_potential=True)
Aligner = gchop.preproc.Aligner(r_cut=30)
Decomposer_0 = gchop.decomposers.JThreshold()

pipe = gchop.GchopPipeline(
        [
        ("transformer_0",Centralizer),
        ("transformer_1",Aligner),
        ("decomposer_0",Decomposer_0)
        ]
    )

First we perform the transformation

In [4]:
tranformed_gal = pipe.transform(gal)

print("Centered:", center.checker(tranformed_gal))
print("Aligned:", align.checker(tranformed_gal))

Centered: True
Aligned: True

And then the decomposition

In [5]:
gal_decomposed = pipe.decompose(gal)

In [6]:
gal_decomposed